### ISSUE TITLE
Provider allows me to change the region of a server in-place (it has no effect)

### ISSUE THREAD

**Issue by thmzlt** [latitudesh/terraform-provider-latitudesh#44]
## Describe the bug

Changing the region of a server is treated as an in-place operation and it has no effect on my account.

### Affected Resource(s)
- latitudesh_server

### Expected Behavior

I expected the server to be recreated in the new region.

### Actual Behavior

```
  # latitudesh_server.my_server will be updated in-place
  ~ resource "latitudesh_server" "my_server" {
        id               = "18029"
      ~ project          = "6501" -> "xxxyyyzzz"
      ~ site             = "SAO" -> "MIA"
        # (6 unchanged attributes hidden)
    }
```

**Terraform version**
```
❯ terraform version
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/latitudesh/latitudesh v0.2.7
```

**Comment by ynhummel** [comment]
@thmzlt, thank you for your contribution! It seems that Terraform is attempting to update the existing server instead of recreating it. A fast way  to force this re-creation would be to change the resource name `"my_server"`.

I'll look into the possibility of making Terraform recognize that this should be a re-creation instead of an update, or at least provide a warning that nothing has changed, instead of falsely indicating that the modification completed successfully.

**Comment by ynhummel** [comment]
In the next update that we are planning, when attempting to change a non-updatable attribute, it will prompt the recreation of the resource avoiding Terraform in-place updates.

Thanks for your contribution @thmzlt!
