### ISSUE TITLE
Cannot import existing resources due to no inventory

### ISSUE THREAD

**Issue by JonathonJulian** [latitudesh/terraform-provider-latitudesh#72]
Hello, I was hoping to Terraform my existing server deployments but it seems the lack of inventory is preventing the import.

```
Error: No available stock found for plan c3.large.x86
```

Is there a workaround for this?

**Comment by ynhummel** [comment]
This is strange, I'll take a look at this issue. Thank you for reporting it!

**Comment by ynhummel** [comment]
Hey @JonathonJulian , sorry about the delay. This month, we updated some parts of the Terraform provider. After some tests, we verified that we can still import even when there's no stock.

To prevent this issue, use the latest provider version ([v1.2.0](https://github.com/latitudesh/terraform-provider-latitudesh/releases/tag/v1.2.0) at the time of writing) and pay attention to:

- The provider accepts plans in the format `c2-small-x86`, using "-" instead of "."
- You have to provide the `plan`, `site`, and `project` attributes exactly as the server already has them. Changing any of these will trigger a force replacement, which will delete your server and recreate it, possibly causing the error message you saw.
- Ensure you are not creating any other server resources or that you are importing to the correct resource block.

Anyway, I hope this helps. Reach out if you still have problems, and we can discuss it!

**Comment by ynhummel** [comment]
Closing this issue as the problem should be resolved. If there’s anything else, please feel free to reopen the issue.
